version: "3.4"
services:
  app:
    image: food-channel-connector:1.0.0
    volumes:
      - ./configs/logs:/app/configs/logs
    ports:
      - "2431:2431"
      - "1431:1431"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2g"
