version: "3.4"
services:
  app:
    image: food-channel-processor:1.0.0
    volumes:
      - ./configs/logs:/app/configs/logs
    ports:
      - "2433:2433"
      - "1433:1433"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2g"
