version: "3.4"
services:
  app:
    image: food-channel-controller:1.0.0
    volumes:
      - ./configs/logs:/app/configs/logs
    ports:
      - "2432:2432"
      - "1432:1432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2g"
